### ISSUE TITLE
test failures on i686-unknown-linux-gnu

### ISSUE THREAD

**Issue by decathorpe** [memorysafety/zlib-rs#134]
I'm working on packaging zlib-rs for Fedora Linux as a dependency of rustls and flate2.

I'm getting test failures on i686-unknown-linux-gnu (our only still-somewhat-supported 32-bit architecture):

```
---- deflate::test::compress_paper_100k stdout ----
thread 'deflate::test::compress_paper_100k' panicked at src/deflate.rs:3638:13:
assertion `left == right` failed
(exact diff excluded because very long)
---- deflate::test::compress_lcet10 stdout ----
thread 'deflate::test::compress_lcet10' panicked at src/deflate.rs:3638:13:
assertion `left == right` failed
(exact diff excluded because very long)
```

Full log:
[cargo-test-i686.log](https://github.com/user-attachments/files/16563291/cargo-test-i686.log)

**Comment by folkertdev** [comment]
interesting. Is this the only test that fails?

our tests test byte-for-byte equivalence with zlib-ng. That is not a requirement, nor a hard promise that we've made, it's just easier for testing to have a "correct" output to aim for.

So if the rest of the test suite succeeds, the code is most likely correct, but our output just off in some places. the output should still be decodable by any compliant zlib implementation. 

Nonetheless, it would be interesting to run our fuzzers for that target, to see if they can narrow down the test case. Maybe I can do that locally by cross-compiling the fuzzer? or do you have dedicated hardware that you could run fuzzers on for this target?

**Comment by decathorpe** [comment]
Yes, these two are the only tests that fail. The full output is in the attached file.

If you're doing a byte-for-byte comparison, I expect that the result might compress to equivalent data but be slightly different. We've seen issues like that with zlib-ng in Fedora before when we switched from zlib to zlib-ng.

Running tests targeting i686 should be relatively straightforward on x86_64. Usually adding `--target i686-unknown-linux-gnu` is enough to make it work after setting up the target with rustup.

**Comment by decathorpe** [comment]
Thanks for looking into it!
