### ISSUE TITLE
Link to report security issues is broken (404)

### ISSUE THREAD

**Issue by Shnatsel** [memorysafety/zlib-rs#201]
The project's [security policy](https://github.com/memorysafety/zlib-rs/security/policy) instructs me to report issues via "our security page", but clicking that link results in a 404 page.

It seems that the URL contains "memory-safety" rather than "memorysafety" as the name of the organization. However, fixing that just brings me back to where I started - the exact same security policy page, not a form to report a vulnerability.

**Comment by folkertdev** [comment]
@squell can you take a look at that when you're back?

@Shnatsel do you have an (urgent) security issue to report?

**Comment by Shnatsel** [comment]
I do not, no.

**Comment by squell** [comment]
The typo is an easy fix (but that link is going to change shortly anyway).

The other problem is that private vulnerability reporting is not enabled for this repository; only a maintainer can do that. Read more about that here:

https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability
